### ISSUE TITLE
`key_file_location` config is still being forced even after `client_secrets` parameter is added

### ISSUE THREAD

**Issue by Atif8Ted** [MeltanoLabs/tap-google-analytics#36] opened 2022-05-16 12:19 UTC
Even after selecting `client_secrets` option for data extraction, `key_file_location` is being given preference even though the `key_file_location` is not added there. 
![Screenshot from 2022-05-16 17-36-55](https://user-images.githubusercontent.com/10879794/168590940-8ffda2fe-013d-4900-8d5e-d6b6080b00fb.png)

- The only workaround is to pass empty string to `key_file_location` and then adding `client_secrets` make the tap use `client_secrets` instead of `key_file_location`.
- I can think the if else condition is creating the issue here.
https://github.com/MeltanoLabs/tap-google-analytics/blob/bc499677f44d2f5ba30ee2c0ebb020ba73edc84a/tap_google_analytics/tap.py#L99

**Comment by pnadolny13** [comment] 2022-06-15 20:42
@Atif8Ted this is a setting of Meltano, it defaults to giving you a `key_file_location` so the code picks that up first even if you have a client_secrets setting configured. See https://github.com/meltano/hub/blob/c8907cd69de11e87a0d7ca6f70d7c579110ad7b8/_data/meltano/extractors/tap-google-analytics/meltanolabs.yml#L31. Youre work around is good. It feels like the Meltano setting shouldnt have a default because theres not an obvious way to rewrite the code to skip that default value.

What do you think?

**Comment by Atif8Ted** [comment] 2022-06-16 16:11
@pnadolny13  . Yes it works for now. But it took me alot of time to actually figure it out. It would be helpful  if this can be added to the documentation somehow.

**Comment by pnadolny13** [comment] 2022-06-16 20:15
@Atif8Ted I would consider this a Meltano bug and not a bug with the tap itself so I'm going to close this issue and move the conversation over to https://github.com/meltano/hub/issues/611 where I've created an issue for us to potentially remove the default value thats causing this.

**Closed by pnadolny13** 2022-06-16 20:15 UTC
